version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 9090:8000
    networks:
      - saudi_cert_network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: saudi_cert_user
      MONGO_INITDB_ROOT_PASSWORD: saudi_cert_password
    volumes:
      - mongodb_data_volume:/data/db
    networks:
      - saudi_cert_network
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: saudi_cert_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: saudi_cert_password
      ME_CONFIG_MONGODB_URL: mongodb://saudi_cert_user:saudi_cert_password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - saudi_cert_network
volumes:
  mongodb_data_volume:
networks:
  saudi_cert_network:
